# Generated by Django 5.0.6 on 2024-06-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_no', models.IntegerField(unique=True)),
                ('e_tax_slab_percentage', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_income_tax',
            },
        ),
        migrations.CreateModel(
            name='EmployeePayScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_no', models.IntegerField(unique=True)),
                ('e_pay_scale', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_pay_scale',
            },
        ),
    ]
