# Generated by Django 5.0.6 on 2024-06-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeeattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeincometax',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employeepayscale',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeeincometax',
            name='e_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeepayscale',
            name='e_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
