# Generated by Django 5.0.6 on 2024-06-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_employeeincometax_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='e_no',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employeeincometax',
            old_name='e_no',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employeepayscale',
            old_name='e_no',
            new_name='employee_id',
        ),
    ]
