# Generated by Django 5.0.6 on 2024-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_e_no_employeeattendance_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeincometax',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
